### GET request to example server
HEAD http://localhost:8000/pets

###
POST http://localhost:8000/pets
Content-Type: application/json
API-Version: 2.0

{
  "name": "Fluffy",
  "species": "dog",
  "age": 5,
  "birth_date": "2018-01-01"
}

###
GET http://localhost:8000/pets
API-Version: 2.0